scopy.asm: wczytywanie do skutku

diff --git a/2023/AKSO/scopy/makefile b/2023/AKSO/scopy/makefile
--- a/2023/AKSO/scopy/makefile
+++ b/2023/AKSO/scopy/makefile
@@ -5,19 +5,18 @@ GDB_FLAGS = -x gdbinit
 SHELL = /bin/bash
 HEX=hexyl #hexdump -C
 
-.PHONY: clean dump test tester maletesty
+G_IN = ./testy/example1.in
+G_OUT = ./testy/example1.out
 
-scopy.o: scopy.asm
+SCOPY_VAR = faultyio.elf # scopy.elf
+
+.PHONY: clean dump test tester maletesty faultyio
+
+%.o: %.asm
 	nasm -f elf64 $(NASMFLAGS) -o $@ $<
 
-rndtest.o: rndtest.asm scopy.asm
-	nasm -f elf64 $(NASMFLAGS) -o $@ $<
-
-scopy.elf: scopy.o
-	ld --fatal-warnings -o $@ $<
-
-rndtest.elf: rndtest.o
-	ld --fatal-warnings -o $@ $<
+%.elf: %.o
+	ld --fatal-warnings -o $@ $^
 
 tester.elf: tester.cpp
 	g++ -std=c++17 $^ -o $@
@@ -26,30 +25,35 @@ dump: scopy.o
 	objdump -M intel -d $^
 	size $^
 
-test: scopy.elf
+test: $(SCOPY_VAR)
 	rm -f ./example1.sout
-	$(TESTER) ./$< ./testy/example1.in ./example1.sout
-	diff --color <($(HEX) ./testy/example1.out) <($(HEX) ./example1.sout)
+	$(TESTER) ./$< $(G_IN) ./example1.sout
+	diff --color <($(HEX) $(G_OUT)) <($(HEX) ./example1.sout)
 
-maletesty: scopy.elf
+maletesty: $(SCOPY_VAR)
 	rm -f ./maletesty/output*
-	for i in {0..10}; do $(TESTER) ./$< ./maletesty/test$$i ./maletesty/output$$i; \
+	for i in {0..10}; do $(TESTER) ./$< ./maletesty/test$$i ./maletesty/output$$i || echo "ERROR!"; \
 		echo "Test $$i:"; \
-		diff --color <($(HEX) ./maletesty/output$$i) <($(HEX) ./maletesty/answer$$i) || true; \
+		diff --color <($(HEX) ./maletesty/output$$i) <($(HEX) ./maletesty/answer$$i) || echo "ERROR!"; \
 	done
 
 tester: tester.elf scopy.elf
 	./$<
 
 rndtest: rndtest.elf
-	for _ in {1..69}; do rm -f ./example1.sout; strace ./$<  ./maletesty/test10 ./example1.sout || echo "ERROR!"; done
+	for _ in {1..69}; do rm -f ./example1.sout; strace ./$<  $(G_IN) ./example1.sout || echo "ERROR!"; done
 
-gdb: scopy.elf
+faultyio: faultyio.elf
+	rm -f ./example1.sout
+	strace ./$< $(G_IN) ./example1.sout
+	diff --color <($(HEX) $(G_OUT)) <($(HEX) ./example1.sout)
+
+gdb: $(SCOPY_VAR)
 	gdb $(GDB_FLAGS) -ex "break _start" $<
 
 strace: scopy.elf
 	rm -f ./example1.sout
-	strace ./$< ./testy/example1.in ./example1.sout
+	strace ./$< $(G_IN) ./example1.sout
 
 clean:
 	rm *.o *.elf *.sout
